export const Urlroutes = {
  reset_pass:"/reset_pass",
  reset_pin:"/reset_pin",
  mobile_privacy: "mobile_privacy",
  mobile_all: "mobile_all",
  mobile_indemnity: "mobile_indemnity",
  mobile_terms: "mobile_terms_terms_and_conditions",
  mobile_altbank_terms: "mobile_altbank_terms",
  dashboard: "/",
  cards: "/cards",
  account: "/account",
  account_statement: "/account/account_req",
  Transactions: "/transaction",
  settings: "/settings",
  hub: "/hub",
  Login: "/login",
  FORGOTPASSWORD: "/forgot-password",
  SecurityQuestions: "/security-question",
  TransactionHistory: "/transaction/transaction-history",
  live_support: "/live_support",
  airtime_data: "/airtime_data",
  AccountUpgrade: "/account/upgrade",
  AccountTransfer: "/transaction/transfer",
  SendMoney: "/transaction/send-money",
  E_Naira: "/transaction/e-naira",
  E_Naira_Dashboard: "/transaction/e-naira-dashboard",
  E_Naira_Transfer: "/transaction/e-naira-transfer",
  successSignup: "/signup_Success",
  SignupOptions: "signup_Options",
  SafSignupStart: "/signup_saf",
  NewSignupStart: "/signup_new",
  Minorsignup: "/minor_signup",
  savingsignup: "/saving_signup",
  futuresignup: "/future_signup",
  SwiftSignUp: "/swift-signup",
  home: "/",
  profile: "/profile",
  EditPersonalInfo: "/profile/edit-info",
  EditNextOfkinInfo: "/profile/edit-nextOfKin",
  EditHouseAddress: "/profile/edit-houseAddress",
  EditMaritalStatus: "/profile/edit-maritalStatus",
  profileDetail: "/profile/detail",
  notification: "/notification",
  PayBills: "/pay-bills",

  topup: "/pay-bills/mobile-topup",
  cableTV: "/pay-bills/cable",
  sportsAndGames: "/pay-bills/sports",
  internetServices: "/pay-bills/internet-services",
  utilities: "/pay-bills/utilities",
  travelAndHotel: "/pay-bills/travel",

  SwiftSignUp: "/swift-signup",

  hub: "/hub",
  altinvest: "/hub/altinvest",
  altmall: "/hub/altmall",
  altdrive: "/hub/altdrive",
  activ8: "/hub/activ8",
  altpower: "/hub/altpower",
  pilgrimage: "/hub/pilgrimage",

  PayBills: "/pay-bills",

  eventTickets: "/pay-bills/event-tickets",
  governmentPayment: "/pay-bills/government-payments",
  SwiftAddStart: "/Swift_Add",
  registerDevice: "/register_device",
  setSecurityQuest: "/setSecu_quest",
  virtualCards: "/virtual_cards",
  account_statement_download: "/account/account_req_download",
  login_set_security: "/login_set_security",

  contact_us: "/contact-us",
  faqs: "/faqs",
  about_us: "/about-us",
  Credits: "/Credits",
  CreditsDetails: "CreditsDetails",
};

export const subAccount = {
  open_account: "open_account",
  upload_docs: "upload_docs",
  // upload_docs: "upload_docs",
  account_statement: "account_statement",
  transaction_history: "transaction_history",
  scheduled_transaction: "scheduled_transaction",
  edit: "edit",
  recurring_transactions: "recurring_transaction",
  recurring_edit: "edit",
  minor_add_account: "minor_add_account",
};

export const subTransaction = {
  Invest: "invest",
  Funds: "funds",
  My_Budgets: "my-budgets",
  add_new: "add_new",
  details: "details",
  edit: "edit",
  add_new_income: "add_new_income",
};
export const subSupports = {
  email: "email",
};
export const subSetings = {
  change_pin: "change_pin",
  change_pass: "change_pass",
  update_sec: "update_sec",
};
export const subSetAccount = {
  share_vibe: "share_vibe",
  refer_a_friend: "refer_a_friend",
  manage_ben: "manage_ben",
  set_trans_limit: "set_trans_limit",
  support_dispute_manage: "support_dispute_manage",
};
